# Generated by Django 3.2.3 on 2021-09-13 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20210913_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='entertainment',
            name='recomended',
            field=models.BooleanField(default=False, verbose_name='Рекомандовано'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hotel',
            name='recomended',
            field=models.BooleanField(default=False, verbose_name='Рекомандовано'),
            preserve_default=False,
        ),
    ]
