# Generated by Django 3.2.3 on 2021-09-13 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20210913_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe',
            name='recomended',
            field=models.BooleanField(default=False, verbose_name='Рекомандовано'),
            preserve_default=False,
        ),
    ]
