# Generated by Django 3.2.3 on 2021-09-17 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_cafe_recomended'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe',
            name='test',
            field=models.BooleanField(default=False, verbose_name='test'),
            preserve_default=False,
        ),
    ]
