# Generated by Django 3.2.3 on 2021-09-17 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20210917_2118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cafe',
            name='test',
        ),
        migrations.RemoveField(
            model_name='entertainment',
            name='test',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='test',
        ),
    ]
