# Generated by Django 3.2.3 on 2021-09-22 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_auto_20210920_1520'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entertainmentimage',
            options={'verbose_name': 'Развлечение изображение', 'verbose_name_plural': 'Развлечения изображения'},
        ),
        migrations.AlterModelOptions(
            name='hotelimage',
            options={'verbose_name': 'Отель изображение', 'verbose_name_plural': 'Отели изображения'},
        ),
        migrations.AlterField(
            model_name='entertainment',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='events.entertainmentcategory', verbose_name='Категория развлечения'),
        ),
    ]
