# Generated by Django 3.2.3 on 2021-10-16 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_auto_20210922_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='entertainment',
            name='price',
            field=models.CharField(blank=True, help_text='Стоимость билета для мастер-класса', max_length=255, verbose_name='Стоимость билета'),
        ),
    ]
