# Generated by Django 3.2.3 on 2021-09-23 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PopularPeople',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('bored', models.CharField(max_length=255, verbose_name='Дата рождения')),
                ('text', models.CharField(max_length=255, verbose_name='Текст')),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Популярный тоболяк',
                'verbose_name_plural': 'Популярные тоболяки',
            },
        ),
    ]
