# Generated by Django 3.2.3 on 2021-09-23 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='popularpeople',
            name='image',
        ),
    ]
