# Generated by Django 3.2.3 on 2021-09-23 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_popularpeople_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='popularpeople',
            name='image',
            field=models.ImageField(default=False, upload_to='', verbose_name='Изображение'),
            preserve_default=False,
        ),
    ]
