# Generated by Django 3.2.3 on 2021-09-24 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_popularpeople_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterestingFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст')),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Интересный факт',
                'verbose_name_plural': 'Интересные факты',
            },
        ),
        migrations.AlterField(
            model_name='popularpeople',
            name='text',
            field=models.TextField(verbose_name='Текст'),
        ),
    ]
