# Generated by Django 3.2.3 on 2021-09-04 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sights', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sight',
            name='email',
            field=models.CharField(blank=True, max_length=255, verbose_name='Email'),
        ),
    ]
