# Generated by Django 3.2.3 on 2021-09-04 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sights', '0002_sight_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sight',
            name='email',
        ),
    ]
