# Generated by Django 3.2.3 on 2021-09-13 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sights', '0003_remove_sight_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='sight',
            name='recomended',
            field=models.BooleanField(default=False, verbose_name='Рекомандовано'),
            preserve_default=False,
        ),
    ]
