# Generated by Django 3.2.3 on 2021-09-13 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sights', '0004_sight_recomended'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sight',
            name='recomended',
        ),
    ]
