# Generated by Django 3.2.3 on 2021-09-20 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sights', '0005_remove_sight_recomended'),
    ]

    operations = [
        migrations.AddField(
            model_name='sight',
            name='views',
            field=models.BigIntegerField(default=0, verbose_name='Просмотры'),
        ),
    ]
