# Generated by Django 3.2.3 on 2021-09-20 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sights', '0006_sight_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sight',
            name='views',
            field=models.PositiveIntegerField(default=0, verbose_name='Просмотры'),
        ),
    ]
